language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
script: composer test
cache:
  directories:
    - Build/Travis/bin
    - Build/Travis/Build
    - Build/Travis/Configuration
    - Build/Travis/Data
    - Build/Travis/Packages
    - Build/Travis/Web
